### ISSUE TITLE
Cannot install requirements from df-translation-client

### ISSUE THREAD

**Issue by Klefo0** [dfint/df-gettext-toolkit#1]
I was using pip3 to install the requirement in df-translation-client, it goes through the first five things, then goes to df-gettext-toolkit, error emerges

![Screenshot 2020-09-20 082026](https://user-images.githubusercontent.com/70630854/93692192-31b6b380-fb1a-11ea-9ba7-a77c299b9b05.png)

Can you solve it?

**Comment by insolor** [comment]
Try `pip install -U -no-cache-dir -r requirements.txt`

**Comment by Klefo0** [comment]
It goes like this
![Screenshot 2020-09-21 092823](https://user-images.githubusercontent.com/70630854/93729040-e5887380-fbec-11ea-878d-c1e5756ce099.png)

**Comment by insolor** [comment]
Try `--no-cache-dir`

**Comment by Klefo0** [comment]
It shows error as the first photo.

**Comment by insolor** [comment]
I've fixed setup.py, try `pip install` again

**Comment by Klefo0** [comment]
It worked! Thank you very much
